export enum StoreKeyEnum {
  'APP_WINDOW_CONFIG' = 'APP_WINDOW_CONFIG',
  'PLAYER_WINDOW_CONFIG' = 'PLAYER_WINDOW_CONFIG',
  'PLAY_LIST_LIST' = 'PLAY_LIST_LIST',
  'PLAY_LIST'= 'PLAY_LIST',
  'PLAY_HISTORY' = 'PLAY_HISTORY',
}